"""Article Migration

Revision ID: 5488bd12618c
Revises: d30e7ee7a8d0
Create Date: 2020-10-30 18:14:15.115744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5488bd12618c'
down_revision = 'd30e7ee7a8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artile_title', sa.String(), nullable=True),
    sa.Column('article_body', sa.String(), nullable=True),
    sa.Column('article_tag', sa.String(), nullable=True),
    sa.Column('article_cover_path', sa.String(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('article_upvotes', sa.Integer(), nullable=True),
    sa.Column('article_downvotes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
