"""Add article comments count column  Migration

Revision ID: 5e44a4becf7a
Revises: f557e3cbc357
Create Date: 2020-10-30 23:18:59.218258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e44a4becf7a'
down_revision = 'f557e3cbc357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('article_comments_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'article_comments_count')
    # ### end Alembic commands ###
